const SHOPPING_LIST = [
    {
        id: 1,
        title: "모션데스크",
        price: 520000,
        category: office,
        src: "../img/모션데스크.jpeg",
    },
    {
        id: 2,
        title: "모션베드",
        price: 1100000,
        category: office,
        src: "../img/모션베드.jpeg",
    },
    {
        id: 3,
        title: "아이맥",
        price: 1190000,
        category: office,
        src: "../img/아이맥.jpeg",
    },
    {
        id: 4,
        title: "닌텐도",
        price: 450000,
        category: office,
        src: "../img/닌텐도.jpeg",
    },
    {
        id: 5,
        title: "플스",
        price: 690000,
        category: office,
        src: "../img/플스.jpeg",
    },
    {
        id: 6,
        title: "버티컬마우스",
        price: 79000,
        category: office,
        src: "../img/버티컬마우스.jpeg",
    },

    {
        id: 7,
        title: "가디건",
        price: 130000,
        category: cloth,
        src: "../img/가디건.jpeg",
    },
    {
        id: 8,
        title: "신발",
        price: 139000,
        category: cloth,
        src: "../img/신발.jpeg",
    },
    {
        id: 9,
        title: "니트",
        price: 220000,
        category: cloth,
        src: "../img/니트.jpeg",
    },
    {
        id: 10,
        title: "무쇠팬",
        price: 88000,
        category: kitchen,
        src: "../img/무쇠팬.jpeg",
    },
    {
        id: 11,
        title: "수비드머신",
        price: 350000,
        category: kitchen,
        src: "../img/수비드머신.jpeg",
    },
];
